### ISSUE TITLE
공통컴포넌트 작업 - Navigation Bar

### ISSUE THREAD

**Issue by D-Sup** [FRONTENDSCHOOL5/final-02-Ta-dak_Ta-dak#5]
- [x] Navigation Bar
- [x] icon 파일 추가
- [x] react-router-dom 모듈설치
- [x] react-inlinesvg 모듈설치

![ezgif-3-41ff6dd707](https://github.com/FRONTENDSCHOOL5/final-02-Ta-dak_Ta-dak/assets/96939334/afa845fc-44ba-441f-843f-e231d729f777)

**Comment by D-Sup** [comment]
- react-inlinesvg 모듈 💡
  - svg를 컴포넌트처럼 사용위한 모듈로  ReactComponent라는 키워드를 통해 구현이 가능합니다
    - ReactComponent는 react-inlinesvg 모듈에서 제공하는 기능으로 ReactComponent를 사용하면 SVG 파일을 React 애플리케이션에서 쉽게 사용할 수 있습니다
```jsx
import { ReactComponent as IconHome } from '../../assets/img/icon-home.svg';
```

**Comment by D-Sup** [comment]
머지 완료했습니다 ~!

**Comment by jiwon6635** [comment]
동섭님 감사합니다~! 수고하셨어용!!
