### ISSUE TITLE
리팩토링 - 코드 수정

### ISSUE THREAD

**Issue by JoWonYeong** [FRONTENDSCHOOL5/final-02-Ta-dak_Ta-dak#67]
- [x] 인풋창 유효성 검사 통과 못했을 때 에러메세지 색상 수정
- [x] 검색, 홈피드, 추천게시글, 팔로잉/팔로워 리스트 스크롤 width 0 주기
- [x] 팔로잉/팔로워 리스트 api 요청 limit, skip 이해해서 무한스크롤 적용하기 (팔로잉/팔로워 리스트 10명만 받아와지는거 수정)
- [x] 본인 팔로잉 안되게 설정
- [x] 프로필 페이지 로딩될 때 처리
- [x] ChatHeader 고쳐서 프로필 페이지에 적용하기 , Chatroom에 보이는 것도 수정
- [x] 게시물 업로드 버튼 누르면 해당 올라간 게시글로 바로 이동하게 수정
- [x] 상품, 게시물리스트, 게시물앨범 순서바꾸기
- [x] 다른사람 프로필에서 냅바의 프로필 클릭하면 본인 프로필로 가게
- [x] 프로필에서 더보기 눌렀을 때 모달창 뜨게
- [x] 모달창 로그아웃 기능 구현

**Comment by jiwon6635** [comment]
확인하고 수정하겠습니다!💻
